### ISSUE TITLE
All folders and requests deleted/missing (reproducable)

### ISSUE THREAD

**Issue by bobs26** [flawiddsouza/Restfox#93]
I have a fairly concerning issue that is easily reproducible for me.

I've been testing/using Restfox for a couple weeks now as an offline replacement to Postman. Up to today, I've been extremely pleased with the client. Up to the end of my day yesterday, everything worked as I hoped and needed it to.

This morning I opened Restfox and suddenly found that all my folders and requests to be completely gone. I tried force refreshes and restarting the app, nothing came back. I checked to see if somehow I had tucked them away in a different collection, but I only have the single/default "my collection" that I'd been using which is empty.

If I create a new folder or request, quit the app, and then re-open it, they will also be deleted. This happens every time without fail for me. 

In a weird twist, if I try to "import" a request and then click the "import into" dropdown, my folders I created in the workspace *are* listed there. And if I choose to import something into those folders, I get a success message but _nothing appears in my sidebar._

From a personal perspective, this kind of behavior is quite concerning. My colleagues that are trialing this client with me have *not* experienced anything like this thus far, so I'm hoping we can identify what might be going on with my client and that this isn't a larger issue.

Not sure what you need to help diagnose the issue. I have *not* done any kind of uninstall/reinstall in case there are files or logs you'd like to collect.

Thanks for looking into this

**Comment by bobs26** [comment]
Update: I created a second workspace to test reproducibility there. When I create new requests and folder in _that_ workspace, quit the app, and then re-open, they do return as I would expect. Switching back to my original workspace the requests/folders are still gone/missing.

So this leads me to believe that there's possible a corruption of some sort with my original Workspace

**Comment by flawiddsouza** [comment]
Hi, can you Ctrl + Shift + i to open Dev Tools? In the console tab you should be seeing an error. I've seen this happen once before when the antivirus at my work got overzealous and deleted the IndexedDB files thinking there was a virus. That happened because we had a virus test file in one of our request bodies to test our virus file removal service but it couldn't understand the difference. This is weirdly specific but something similar might've happened for you. By the way, what's the platform you're using the client on?

**Comment by bobs26** [comment]
Hey! Thanks for replying. I'm using MacOS Sonoma 14.3.1.

Client had an update which I installed and retested, but the issue remained. As a reminder, it's only impacting a single workspace; I've created a couple additional workspaces and added requests/folders to it and have not been able to reproduce the issue. But my original workspace continues to behave exactly as I originally described.

I am indeed getting a console error on the `bad` workspace:
```html
TypeError: Cannot read properties of undefined (reading 'children')
    at toTree (index-460a22db.js:498:67217)
    at Store.setCollection (index-460a22db.js:531:21094)
    at index-460a22db.js:8:4106
    at index-460a22db.js:8:14901
    at Array.forEach (<anonymous>)
    at index-460a22db.js:8:14875
    at Store._withCommit (index-460a22db.js:8:17341)
    at Store.commit (index-460a22db.js:8:14846)
    at Store.commit (index-460a22db.js:8:14010)
    at Proxy.fetchSetCollectionForWorkspace (index-460a22db.js:723:124114)
```

**Comment by flawiddsouza** [comment]
Thanks for checking. This seems like a new issue. Is there some way you can give me the workspace data?

1st way is by clicking on the export button in your workspace:
![image](https://github.com/flawiddsouza/Restfox/assets/10164500/5a49b537-b4aa-4f6b-a97d-0b302f85d8ec)

If that's not working, then you can download the full backup of the application using: 
![image](https://github.com/flawiddsouza/Restfox/assets/10164500/ca7ef75e-1231-423f-99a7-142fe898ddad)

Please redact / remove all sensitive data / urls from downloaded json file before uploading it here.

This will help me reproduce the issue on my side.
